# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Build source, tests and run tests with coverage
#- script: |
#    dotnet test ./PayPalNvpClient.Tests/PayPalNvpClient.Tests.Unit/PayPalNvpClient.Tests.Unit.csproj -c Debug --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
#  displayName: 'Build source, tests and run tests with coverage'

# Upload coverage to codecov.io
#- script: |
#    %USERPROFILE%\.nuget\packages\codecov\1.1.1\tools\codecov.exe -f "./PayPalNvpClient.Tests/PayPalNvpClient.Tests.Unit/coverage.opencover.xml" -t $(CODECOV_TOKEN)
#  displayName: Upload coverage to codecov.io

- task: ArchiveFiles@2
  displayName: Archive $(Build.SourcesDirectory)
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    
- task: PublishBuildArtifacts@1
  displayName: Publish Artifact PayPalNvpClient
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: PayPalNvpClient